services:
  recon:
    build: .
    image: recon-tool
    env_file: .env
    environment:
      - SHODAN_API_KEY=${SHODAN_API_KEY}
      - GITHUB_SEARCH_TOKEN=${GITHUB_SEARCH_TOKEN}
    stdin_open: true  # -i equivalent
    tty: true         # -t equivalent
    volumes:
      - .:/app
    working_dir: /app