services:
  recon:
    build: .
    image: recon-tool
    ports:
      - "5000:5000"
    volumes:
      - .:/app
    environment:
        # API Keys, .env dosyasında bulunuyor.
      - SHODAN_API_KEY=${SHODAN_API_KEY}
      - GITHUB_SEARCH_TOKEN=${GITHUB_SEARCH_TOKEN}
      - TELEGRAM_TOKEN=${TELEGRAM_TOKEN}
      - ALLOWED_USER_IDS=${ALLOWED_USER_IDS}
      - ALLOWED_CHAT_IDS=${ALLOWED_CHAT_IDS}
    stdin_open: true  # -i equivalent
    tty: true         # -t equivalent
